### ISSUE TITLE
Cannot share mountpoint between containers (host is fine)

### ISSUE THREAD

**Issue by nicolaspernoud** [Salokyn/docker-s3ql#1]
Hi,

Thanks for your works that takes away the pain of setting up the all python stuff to mount an s3 container.

I use your image with scaleway object storage and it works fine **as long as I mount the s3ql fs on the host**. But I cannot manage to access the mounted storage from another container.

The docker-s3ql container is started with `-v /data/s3:/s3ql:rw,rshared` and the other container is started (after) with `-v /data/s3:/data/s3:slave'`. When I do a `ls /data/s3` on this container, I get an "Permission denied" error.

Does this container must have fuse capability ? Any other idea ?

I am aware that my question could be more related to docker to your container, but any help would be welcome.

Best regards.

**Comment by Salokyn** [comment]
Hello,

The docker-s3ql container mount the FS as root. By default S3QL let only the user that mounted the FS access to it (to root in that case).

Is the user trying to access `/data/s3` root or someone else?

Try to specify the [env variable](https://github.com/Salokyn/docker-s3ql#environment-variables)  `S3QL_MOUNT_OPTIONS='--allow-other'`

**Comment by nicolaspernoud** [comment]
Hello,

That did the trick. Thanks a lot !

Best regards.
